# Utiliser l'image Node.js 20.11
FROM node:20.11.0

# Configurer le répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers de l'application
COPY ./app .

# Installer les dépendances de l'application
RUN npm install

# Fix les permissions (optionnel)
RUN chmod -R 755 /usr/src/app

# Installer react-scripts
RUN npm install react-scripts --save

# Construire l'application React
RUN npm run build

# Installer serve pour servir l'application
RUN npm install -g serve

# Exposer le port 3000
EXPOSE 3000

# Commande pour lancer l'application
CMD ["serve", "-s", "build"]
