# Use Node.js 20.11
FROM node:20.11.0 AS build

# Set the working directory
WORKDIR /usr/src/app

# Copy the application files
COPY ./app .

# Install application dependencies
RUN npm install

# Ensure react-scripts has execute permissions
RUN chmod +x node_modules/.bin/react-scripts

# Build the React application
RUN npm run build

# Production stage
FROM node:20.11.0 AS production

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/build ./build

# Install serve to serve the application
RUN npm install -g serve

# Expose port 3000
EXPOSE 3000

# Command to start the application
CMD ["serve", "-s", "build"]
